### PR TITLE
[#91]feat: implement pgmoneta-cli decrypt

### PR DESCRIPTION
**Pull request by solokyo**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
I get

```
2022-09-11 15:46:36 DEBUG main.c:1222 pgmoneta: Management decrypt: /tmp/primary-20220911154517.tar.zstd.aes/(null)
```

and

```
2022-09-11 15:46:37 WARN  management.c:1437 pgmoneta_management_read_int32: read: 3 Invalid argument
```

**Comment by jesperpedersen** [comment]
Simple fix.

**Comment by jesperpedersen** [comment]
Fixed, rebased, and merged.

Thanks for your contribution !

**Comment by solokyo** [comment]
```c
   for (int i = 0; i < number_of_returns; i++)
   {
      pgmoneta_management_read_int32(ssl, socket, &code);
   }
```
Unused payloads also need to deal with. Roger that.

Thanks for helping me fix the bug.

**Pull request closed without merging**
