### PR TITLE
Supporting Lz4 compression

### PR DESCRIPTION
**Pull request by MariamFahmy98**

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Looks good, but could you make sure that indentation is 3 spaces ? Commit, squash, force. Thanks !

As a follow-up you could reconsider a refactoring of the gzip and zstd part to be called `..._compression.[h|c]` as well...

**Comment by MariamFahmy98** [comment]
I have made a separate commit for refactoring gzip and zstd, shall I squash it too ?
I have modified the indentation to 3 spaces too.
Thanks.

**Comment by jesperpedersen** [comment]
Looks good - but I would rather merge this as two separate pull requests, so could you move the refactoring patch to another branch and `reset --hard` this one with a force ?

**Comment by jesperpedersen** [comment]
Sorry, I forgot - could you `commit --amend` the title to include `[#7] Support Lz4 compression` ?

**Comment by MariamFahmy98** [comment]
Done, Thanks.

**Comment by jesperpedersen** [comment]
Please, rebase on main, and force

**Pull request merged**
