### PR TITLE
[#198] Apply line parsing for configurations files, fix free memory a…

### PR DESCRIPTION
**Pull request by AhmedHisham99**
i created new branch for merging all commits
now it's ready to merge

### CODE REVIEW

**Comment by AhmedHisham99** [comment]
I have created squash and force push
can you please check this out.
@jesperpedersen

**Comment by jesperpedersen** [comment]
Can you rebase ? Also, ddin't you have changes to the `pgmoneta_remove_whitespace()` function ?

https://www.git-tower.com/learn/git/faq/git-squash
https://github.com/progit/progit2/releases/tag/2.1.421

**Comment by jesperpedersen** [comment]
Any updates ? Are you stuck on something ?

**Comment by jesperpedersen** [comment]
Please, reopen if you are planning to work on this

**Pull request closed without merging**
