### PR TITLE
[#401] CLI: conf get | set | ls

### PR DESCRIPTION
**Pull request by MohanadKh03**
Currently this contains the logic for ``conf get`` which works as expected and similar to the other commands. If all is good with this way it will basically be the same idea for ``conf set`` and ``conf ls``  

Got a problem with double free though not sure I tried debugging through the changed parts and even stopped freeing anything myself in ``configuration.c`` , But still this comes up ``free(): double free detected in tcache 2`` so any ideas how I can fix this ? Is there a better way to look through this other than gdb or manual printing/debugging ?

### CODE REVIEW

**Comment by jesperpedersen** [comment]
I think we need to think about how we can send the entire configuration file over, and then filter the key we need out. So, it is like the translate feature, f.ex. `conf get host` will give `[pgmoneta]`'s `host` setting, and `conf get primary.host` will give `[primary]`'s `host` setting.

`conf ls` is a lot easier.

`conf set` can either get the configuration, set the value, and send it back - or - just the single value back. Doing the former is likely better long term

**Comment by jesperpedersen** [comment]
For the double `free()` - make sure that you compile with `Debug` and `clang`, and maybe track the `free()` with a `bool`

**Comment by MohanadKh03** [comment]
> I think we need to think about how we can send the entire configuration file over, and then filter the key we need out. 

Can we not just filter the arguments passed by section (if found then we find the corresponding key otherwise ``pgmoneta``'s section by default) and the config key instead of sending the whole file and then filtering what we need ?  I think sending the whole configuration just to get a single value is not worth it  we could just do a single key-value 
WDYT ? @jesperpedersen

**Comment by jesperpedersen** [comment]
@MohanadKh03 Sure, we can start that way.

I'm just thinking further ahead, where a client want all values, and the server version might be different than the client - or even not our CLI

**Comment by jesperpedersen** [comment]
Look at functions like https://github.com/pgmoneta/pgmoneta/blob/main/src/cli.c#L1475 and friends, and think about passing the JSON request / result from `cli.c` -> `management.c` -> `main.c` -> `configuration.c`.

The two middle ones should almost be a copy'n'paste...

**Comment by jesperpedersen** [comment]
I would rather see if we could get it correct the first time.

For `set` you would transform the JSON into a `struct configuration` and call https://github.com/pgmoneta/pgmoneta/blob/main/src/libpgmoneta/configuration.c#L3037

**Comment by MohanadKh03** [comment]
Not sure If i got this right but this is how I see it
We first create the request in ``cli.c`` sending only the key in the payload e.g: ``conf get host`` , ``conf get primary.host`` by using ``management.c`` then this is read in ``main.c``'s event loop and the payload sent is received by calling the function in ``configuration.c`` which should be modified rn to accept other servers e.g ``conf get primary.host`` and put the corresponding value (if found) )in its response right ?
So basically now I just need to fix the receiving part am I right ? ``conf ls`` it is pretty easy and ``conf set`` is just sending the configuration file over (tbh I think just sending the key is enough but since you think sending it over is better for the long term then alright) to the receiver part and then at ``configuration.c`` it calls https://github.com/pgmoneta/pgmoneta/blob/main/src/libpgmoneta/configuration.c#L3037

Do I get this correct now ? Cuz I got kind of confused when reading the ``translate`` parts in ``cli.c``

**Comment by jesperpedersen** [comment]
Yeah, so `conf get` will get the whole configuration as a JSON object, so don't need the "3rd" parameter. Then `cli.c` will filter out the correct value based on the "3rd".

`conf set` will do `conf get`, modify, and send back, then `main.c` will delegate to `configuration.c` to change the actual value if possible

**Comment by jesperpedersen** [comment]
The "translate" part is the extraction of the value from `conf get XYZ` - think https://jqlang.github.io/jq/ - as SMALL as you can make it

**Comment by jesperpedersen** [comment]
it would be the same in `doc/CONFIGURATION.md` and `doc/manual/user-02-configuration.md`

**Comment by MohanadKh03** [comment]
Yes ill handle the docs for it in the Advanced Guide 
Apologies for being late though as I am a bit busy but by the end of the week it will be done both implementation and docs

**Comment by jesperpedersen** [comment]
Just take your time to find the best solution

**Comment by MohanadKh03** [comment]
@jesperpedersen Sorry for being late

 I tried the whole thing again and implemented the ``conf ls`` easily but in the ``conf get`` and ``conf set`` you said we should 
 > I think we need to think about how we can send the entire configuration file over, and then filter the key we need out. So, it is like the translate feature, f.ex. conf get host will give [pgmoneta]'s host setting, and conf get primary.host will give [primary]'s host setting.

but if we go through this approach starting from ``cli.c`` -> ``management.c`` -> ``main.c`` -> ``configuration.c`` we would not send the configuration file over right ? we will just receive the key-value that is given to us , So could you please elaborate what exactly do you mean by send the entire configuration file over? Do you mean not sending the ``config_key`` in here ? https://github.com/pgmoneta/pgmoneta/blob/33b9fde6d0951c7e9a40631518465fa60d3ab567/src/libpgmoneta/management.c#L482
As far as I understand clients - even non-CLI clients - will be forced to write their own logic of handling the config file so I think it would be better handling the config file at ``configuration.c`` which is kind of the pgmoneta-server-side right ?

**Comment by jesperpedersen** [comment]
You need to make a representation of `pgmoneta.conf` in JSON format.

So, in `management.h` you will do

```
#define MANAGEMENT_CONFIGURATION_HOST  "Host"
#define MANAGEMENT_CONFIGURATION_PORT  "Port"
...
```

and then in `configuration.c` in `pgmoneta_configuration_get` fill out the JSON document with `struct configuration` and include the `struct server`s too.

The `pgmoneta_configuration_set` you should get a key/value pair in the `Request` part that you parse to an entry in `struct configuration` or in one of the `struct server`s

**Comment by jesperpedersen** [comment]
Superseeded by #409

**Pull request closed without merging**
