### PR TITLE
[#269] Direct IO

### PR DESCRIPTION
**Pull request by shikharish**
@jesperpedersen

### CODE REVIEW

**Comment by jesperpedersen** [comment]
You need to investigate why `pgmoneta-cli backup primary` takes so long - its 2 sec vs 17 sec

**Comment by shikharish** [comment]
I don't see where it took 17sec. On my system the results with and without the patch are similar.

2 backups With O_DIRECT:
```
vscode ➜ /workspaces/pgmoneta/build/src (direct-io) $ ./pgmoneta-cli -c pgmoneta.conf backup primary     
Header: 
  ClientVersion: 0.15.0
  Command: 1
  Output: 0
  Timestamp: 20241006193213
Outcome: 
  Status: true
  Time: 00:00:03
Request: 
  Server: primary
Response: 
  Backup: 20241006193213
  BackupSize: 6258688
  Compression: 2
  Encryption: 0
  MajorVersion: 17
  MinorVersion: 0
  RestoreSize: 40222720
  Server: primary
  ServerVersion: 0.15.0
vscode ➜ /workspaces/pgmoneta/build/src (direct-io) $ ./pgmoneta-cli -c pgmoneta.conf backup primary
Header: 
  ClientVersion: 0.15.0
  Command: 1
  Output: 0
  Timestamp: 20241006193218
Outcome: 
  Status: true
  Time: 00:00:02
Request: 
  Server: primary
Response: 
  Backup: 20241006193218
  BackupSize: 3969024
  Compression: 2
  Encryption: 0
  MajorVersion: 17
  MinorVersion: 0
  RestoreSize: 40222720
  Server: primary
  ServerVersion: 0.15.0
```

2 backups without O_DIRECT (main branch):
```
vscode ➜ /workspaces/pgmoneta/build/src (main) $ ./pgmoneta-cli -c pgmoneta.conf backup primary
Header: 
  ClientVersion: 0.15.0
  Command: 1
  Output: 0
  Timestamp: 20241006193347
Outcome: 
  Status: true
  Time: 00:00:01
Request: 
  Server: primary
Response: 
  Backup: 20241006193347
  BackupSize: 16146432
  Compression: 2
  Encryption: 0
  MajorVersion: 16
  MinorVersion: 3
  RestoreSize: 220741632
  Server: primary
  ServerVersion: 0.15.0
vscode ➜ /workspaces/pgmoneta/build/src (main) $ ./pgmoneta-cli -c pgmoneta.conf backup primary
Header: 
  ClientVersion: 0.15.0
  Command: 1
  Output: 0
  Timestamp: 20241006193350
Outcome: 
  Status: true
  Time: 00:00:02
Request: 
  Server: primary
Response: 
  Backup: 20241006193350
  BackupSize: 5312512
  Compression: 2
  Encryption: 0
  MajorVersion: 16
  MinorVersion: 3
  RestoreSize: 220741632
  Server: primary
  ServerVersion: 0.15.0
```

**Comment by shikharish** [comment]
updated the comment  - was mistakenly using different postgresql version on different branches

**Comment by Jubilee101** [comment]
Tried it as well, yeah, the result was similar to what @shikharish had.

**Comment by jesperpedersen** [comment]
So, `O_DIRECT` is slower...

**Comment by jesperpedersen** [comment]
We need another design... we can't have all these `fcntl` / `malloc` calls per `pgmoneta_write_file` .

There can only be 1 call per `fd`...

**Comment by jesperpedersen** [comment]
`pgmoneta_write_file()` should basically be just the `write()` call.

The memory buffer for the call should be a memory aligned buffer based on the disk buffer size.

If `O_DIRECT` isn't supported then it should be transparent to the `pgmoneta_write_file()`  call -- if we even need that function

**Comment by shikharish** [comment]
@jesperpedersen The O_SYNC flag is the reason for the comparatively slower speed. Using only O_DIRECT gives faster results:

```
vscode ➜ /workspaces/pgmoneta/build/src (direct-io) $ ./pgmoneta-cli -c pgmoneta.conf backup primary           
Header: 
  ClientVersion: 0.15.0
  Command: 1
  Output: 0
  Timestamp: 20241008065106
Outcome: 
  Status: true
  Time: 00:00:01
Request: 
  Server: primary
Response: 
  Backup: 20241008065106
  BackupSize: 6258688
  Compression: 2
  Encryption: 0
  MajorVersion: 17
  MinorVersion: 0
  RestoreSize: 40222720
  Server: primary
  ServerVersion: 0.15.0
vscode ➜ /workspaces/pgmoneta/build/src (direct-io) $ ./pgmoneta-cli -c pgmoneta.conf backup primary
Header: 
  ClientVersion: 0.15.0
  Command: 1
  Output: 0
  Timestamp: 20241008065109
Outcome: 
  Status: true
  Time: 00:00:01
Request: 
  Server: primary
Response: 
  Backup: 20241008065109
  BackupSize: 3969024
  Compression: 2
  Encryption: 0
  MajorVersion: 17
  MinorVersion: 0
  RestoreSize: 40222720
  Server: primary
  ServerVersion: 0.15.0
```

Is it necessary to use the O_SYNC flag? I am sure the speed for buffered-io will also decrease if we use the O_SYNC flag.

**Comment by jesperpedersen** [comment]
We can flush the file before closing it, but we also need to change `pgmoneta_write_file()` such that we don't have all these system calls, then it will be faster

**Comment by jesperpedersen** [comment]
You can try `posix_fadvise()` with `POSIX_FADV_SEQUENTIAL` once the file is opened if `#ifdef HAVE_LINUX`

**Comment by shikharish** [comment]
If we make `pgmoneta_write_function()` completely transparent to direct and buffered writes, we would have to do the same work outside of the function for every write operation. For ex., any odd-byte sized write operation *has* to be done with O_DIRECT disabled, so we will have to add this check. 

I have made some updates to the PR:
- `pgmoneta_write_function()` will only check for misalignment - if zero, proceeds to write with O_DIRECT - if non-zero, disables O_DIRECT, writes file, renable O_DIRECT
- remove O_SYNC
- add `fsync()` calls

Tested backup with this patch on a larger database - 1:03sec vs  1:09sec without patch(main branch)

**Comment by shikharish** [comment]
To give an idea, out of 11509 `write()` calls,
- 6399 were direct-io (from `wal.c`) 
  - out of which 259 were with misalignment(so new buffer was malloced and data copied for each call)
- 5110 were buffered-io (from `message.c`)
  - almost all were with misalignment which was not fixed

**Comment by jesperpedersen** [comment]
@shikharish Still doing ok ?

**Comment by jesperpedersen** [comment]
@shikharish Still want to work on this ?

**Comment by shikharish** [comment]
Yes, give me a few more days please.

**Comment by jesperpedersen** [comment]
Don't worry about it, it is a matter of keeping the pull request rebased so it can be applied easily, and communicate about what issues you are having, or things you are working on

**Comment by shikharish** [comment]
The final solution I think is to change the way we parse any `message` we get from the database. Currently, we store all the data in `message->data` and that is the issue. I am working on changing the api in message.c so that `message->data` only contains the actual data of the message and `message->length` contains only the length of the actual message. And when we need to write the message, we can re-construct it to follow pgprotocol.

**Comment by shikharish** [comment]
It is a bit complicated to cover all cases of the message types such that any write will follow the alignment rules of O_DIRECT. For ex., when writing wal data('w') to file we skip the first 25 bytes so will have to handle that case differently.

**Comment by jesperpedersen** [comment]
@shikharish I think this is way too complex for what we will gain kernel space usage, and disk I/O. Furthermore, the whole message infrastructure will be complicated and harder to maintain.

I think for now we should just shelve the project, and only reopen if we have a very good and simple idea that will work. We have a lot of tasks to work on which I would rather see completed.

I think it is great that you have investigated this area so we now know what pitfalls there are.

Thanks !

**Comment by shikharish** [comment]
@jesperpedersen Alright. Working on this was really interesting. I will keep this in the back of my mind for now. And work on other tasks. Thanks.

**Pull request closed without merging**
