### PR TITLE
[#100] Supporting backup in Azure storage account

### PR DESCRIPTION
**Pull request by MariamFahmy98**

### CODE REVIEW

**Comment by MariamFahmy98** [comment]
For testing purposes, I am trying to upload the `backup.info` in the Azure storage account. There is an issue in the authorization header. As a result request can't be authenticated and it fails.

Here is a sample of the output I got:
```
> PUT /pgmoneta-continer/backup-dir/primary/backup/20221108004806backup.info HTTP/1.1
Host: pgmoneta.blob.core.windows.net
Accept: */*
Authorization: Authorization: SharedKey pgmoneta:Z/zxvtq44WgcHNvs+aLD9INpjH43al0B4slTCxkPK6E=
x-ms-blob-type: BlockBlob
x-ms-date: Mon, 07 Nov 2022 22:48:06 GMT
x-ms-version: 2021-08-06
Content-Length: 94
Expect: 100-continue

* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
< Content-Length: 321
< Content-Type: application/xml
< Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
< x-ms-request-id: b8887769-a01e-0050-34fb-f222ae000000
< Date: Mon, 07 Nov 2022 22:48:07 GMT
* HTTP error before end of send, stop sending
< 
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b8887769-a01e-0050-34fb-f222ae000000
* Closing connection 0
```
I tried to construct the request manually using a bash script and it seems that the signing key isn't decoded correctly. I'll do my best to figure it out.

**Comment by MariamFahmy98** [comment]
It finally works, Here is a snapshot of the backup in azure :)
image

**Comment by MariamFahmy98** [comment]
Empty directories are finally uploaded, Here is a snapshot of the work done so far:
image

Empty directories have an empty `.pgmoneta` file:
image

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Pull request merged**
