### PR TITLE
[#262] Fix password generation issue

### PR DESCRIPTION
**Pull request by joanjeremiah**
Removed #' and ';' characters from the list of characters used in password generation like discussed in issue#262

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Please, use

```
[#262] https://github.com/pgmoneta/pgmoneta/issues/262
```

as the commit message

**Comment by joanjeremiah** [comment]
> Please, use
> 
> ```
> [#262] https://github.com/pgmoneta/pgmoneta/issues/262
> ```
> 
> as the commit message

I changed the commit message

**Comment by jesperpedersen** [comment]
I fixed the commit message

**Comment by jesperpedersen** [comment]
Rebased, and merged.

Thanks for your contribution !

**Comment by joanjeremiah** [comment]
> Rebased, and merged.
> 
> Thanks for your contribution !

I'm thrilled to have contributed. I'm eager to continue contributing and would appreciate any new tasks or issues you could assign me. Looking forward to the next opportunity

**Comment by jesperpedersen** [comment]
You can look for tasks yourself as well -- figure out what is missing, from documentation to new features.

Otherwise reach out through the forum or in private

**Pull request closed without merging**
